### ISSUE TITLE
Wrong Seed

### ISSUE THREAD

**Issue by chukleberryfinn** [hube12/MinecraftSeedCrackingC#6]
Using at least 6 end cities, 3 unique biomes (giant tree taiga, lukewarm ocean and swamp) I was able to get a potential seed but no final seed. In Neil video, it shows a different seed in game than he gets from the cmd result. Any explanation?

**Comment by hube12** [comment]
final seeds are the only seeds that matters all the other seeds put inside the console are steps seeds, meaning they are partial ones, please refer to the "you made a mistake while gathering data part guide inside the readme"

**Comment by hube12** [comment]
also 6 end cities... you clearly didn't understand the diversity clause...
