### ISSUE TITLE
Overworld terrain only

### ISSUE THREAD

**Issue by EdwoG** [hube12/MinecraftSeedCrackingC#7]
Is there a way to only fill in biomes?
my server seems to have spigot paper so the end has a diffrent seed or something.

If we only fill in rare biome coords and three way crossing with biomes.
Wouldnt that be sufficient to search for the overworld terrain seed?

**Comment by hube12** [comment]
nope

**Comment by hube12** [comment]
too slow to crack with only biomes

**Comment by hube12** [comment]
go at GPUExample -> need 9 structures, i will not help with that, it dont give support anymore
